local __ust = __util.str
local __uso = __util.str_opt
local __usf = __util.strref
local __uss = __util.secure_state
local __ucf = __util.strcref
local __uce = __util.cast_enum
local __utvec2 = __util.cast_vec2
local __utvec3 = __util.cast_vec3
local __utvec4 = __util.cast_vec4
local __utrgb = __util.cast_rgb
local __utrgbm = __util.cast_rgbm
local __utenum = __util.cast_enum
local __utmat3x3 = __util.cast_mat3x3
-- local __utmat4x4 = __util.cast_mat4x4